name: polaris

type: node

up:
  - node:
      version: v14.17.6

open:
  app: http://localhost:3000/

commands:
  server: npm run dev
  start: npm run start
  test: npm run test
  build: npm run build
