import type {NextPage} from 'next';
import Head from 'next/head';
import React from 'react';
import {
  getBreakpointTokens,
  getColorTokens,
  getMotionTokens,
  getSpacingTokens,
  getTypographyTokens,
} from '../../packages/functions';
import {TokenValue} from '../../packages/functions/types';
import {SUPPORTED_FORMATS} from './api/beta/tokens';

const Home: NextPage = () => {
  const colorTokens = getColorTokens();
  const spacingTokens = getSpacingTokens();
  const motionTokens = getMotionTokens();
  const breakPointTokens = getBreakpointTokens();
  const typographyTokens = getTypographyTokens();

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>WIP Tokens</h1>
      <p>These tokens can also be fetched through the API:</p>
      <ul>
        {SUPPORTED_FORMATS.map((format) => (
          <li key={format}>
            <a href={`api/beta/tokens?format=${format}`}>
              In {format.toUpperCase()} format
            </a>
          </li>
        ))}
      </ul>

      <h2>Color tokens</h2>
      {Object.entries(colorTokens).map(([key, value]) => {
        return (
          <TokenRow
            key={key}
            name={key}
            value={value.value}
            aliasOf={value.aliasOf}
            description={value.description}
          >
            <div
              style={{
                width: 30,
                height: 30,
                borderRadius: 100,
                background: value.value,
              }}
            ></div>
          </TokenRow>
        );
      })}

      <h2>Spacing tokens</h2>
      {Object.entries(spacingTokens).map(([key, value]) => {
        return (
          <TokenRow
            key={key}
            name={key}
            value={value.value}
            aliasOf={value.aliasOf}
            description={value.description}
          >
            <div
              style={{
                width: 30,
                height: value.value,
                background: `rgba(255,255,255,.1)`,
                boxShadow: `inset 0 -1px #666, inset 0 1px #666`,
              }}
            ></div>
          </TokenRow>
        );
      })}

      <h2>Typography tokens</h2>
      {Object.entries(typographyTokens).map(([key, value]) => {
        return (
          <TokenRow
            key={key}
            name={key}
            value={value.value}
            aliasOf={value.aliasOf}
            description={value.description}
          >
            &nbsp;
          </TokenRow>
        );
      })}

      <h2>Motion tokens</h2>
      {Object.entries(motionTokens).map(([key, value]) => {
        return (
          <TokenRow
            key={key}
            name={key}
            value={value.value}
            aliasOf={value.aliasOf}
            description={value.description}
          >
            &nbsp;
          </TokenRow>
        );
      })}

      <h2>Breakpoint tokens</h2>
      {Object.entries(breakPointTokens).map(([key, value]) => {
        return (
          <TokenRow
            key={key}
            name={key}
            value={value.value}
            aliasOf={value.aliasOf}
            description={value.description}
          >
            &nbsp;
          </TokenRow>
        );
      })}
    </div>
  );
};

const TokenRow = ({
  name,
  value,
  aliasOf,
  description,
  children,
}: {
  name: string;
  value?: TokenValue;
  aliasOf?: string;
  description: string;
  children: React.ReactNode;
}) => {
  return (
    <div className="token-row">
      <div className="token-row__preview">{children}</div>
      <div className="token-row__name">
        <h3>{name}</h3>
      </div>
      <div className="token-row__value">
        <p>
          {value ? (
            value
          ) : (
            <>
              <span className="token-row__value__alias">Alias &rarr;</span>{' '}
              {aliasOf}
            </>
          )}
        </p>
      </div>
      <div className="token-row__description">
        <p>{description}</p>
      </div>
    </div>
  );
};

export default Home;
