import type {NextPage} from 'next';
import Head from 'next/head';
import React from 'react';
import {
  createColorTokens,
  createMotionTokens,
  createSpacingTokens,
} from '../../packages/functions';
import {TokenValue} from '../../packages/functions/types';

const Home: NextPage = () => {
  const colorTokens = createColorTokens({
    successHue: 100,
    warningHue: 0,
  });
  const spacingTokens = createSpacingTokens({multiple: 1});
  const motionTokens = createMotionTokens();

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>WIP Tokens</h1>
      <h2>Color tokens</h2>
      {Object.entries(colorTokens).map(([key, value]) => {
        return (
          <TokenRow
            key={key}
            name={key}
            value={value.value}
            description={value.description}
          >
            <div
              style={{
                width: 30,
                height: 30,
                borderRadius: 100,
                background: value.value,
              }}
            ></div>
          </TokenRow>
        );
      })}

      <h2>Spacing tokens</h2>
      {Object.entries(spacingTokens).map(([key, value]) => {
        return (
          <TokenRow
            key={key}
            name={key}
            value={value.value}
            description={value.description}
          >
            <div
              style={{
                width: 30,
                height: value.value,
                background: `rgba(255,255,255,1)`,
              }}
            ></div>
          </TokenRow>
        );
      })}

      <h2>Motion tokens</h2>
      {Object.entries(motionTokens).map(([key, value]) => {
        return (
          <TokenRow
            key={key}
            name={key}
            value={value.value}
            description={value.description}
          >
            ...
          </TokenRow>
        );
      })}
    </div>
  );
};

const TokenRow = ({
  name,
  value,
  description,
  children,
}: {
  name: string;
  value: TokenValue;
  description: string;
  children: React.ReactNode;
}) => {
  return (
    <div className="token-row">
      <div className="token-row__preview">{children}</div>
      <div className="token-row__meta">
        <h3>{name}</h3>
        <p>{description}</p>
      </div>
      <div className="token-row__value">
        <p>{value}</p>
      </div>
    </div>
  );
};

export default Home;
