import React from 'react';
import Head from 'next/head';
import {Button} from '@polaris/elements';

export default function Home() {
  const sparklesLabel = 'sparkles';

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Button variant="primary">
          Polaris{' '}
          <span role="img" aria-label={sparklesLabel}>
            ✨
          </span>
        </Button>
      </main>
    </>
  );
}
